[group:trident-test]
programs=trident-test-web

[program:trident-test-web]
directory=/data2/trident_test/trident
command=/data2/trident_test/venv/bin/python run.py --port=6001 --logging=debug
environment=USER="docker_test",ENV=test
stderr_logfile=/var/log/supervisor/trident-test-web-stderr.log
stdout_logfile=/var/log/supervisor/trident-test-web-stdout.log
user=docker_test
autostart=true
autorestart=true
startsecs=5
startretries=3
startsecs=1