# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\"\x8d\x01\n\nRPCRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\x12%\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x16.RPCRequest.FilesEntry\x1a;\n\nFilesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.RequestFiles:\x02\x38\x01\"+\n\x0cRequestFiles\x12\x1b\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0c.RequestFile\"-\n\x0bRequestFile\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"a\n\x08RPCReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0c\n\x04\x66ile\x18\x05 \x01(\x0c\x12\x0c\n\x04text\x18\x06 \x01(\tb\x06proto3'
)




_RPCREQUEST_FILESENTRY = _descriptor.Descriptor(
  name='FilesEntry',
  full_name='RPCRequest.FilesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RPCRequest.FilesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RPCRequest.FilesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=158,
)

_RPCREQUEST = _descriptor.Descriptor(
  name='RPCRequest',
  full_name='RPCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RPCRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='RPCRequest.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='files', full_name='RPCRequest.files', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RPCREQUEST_FILESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=158,
)


_REQUESTFILES = _descriptor.Descriptor(
  name='RequestFiles',
  full_name='RequestFiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='RequestFiles.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=203,
)


_REQUESTFILE = _descriptor.Descriptor(
  name='RequestFile',
  full_name='RequestFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='RequestFile.body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='RequestFile.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=250,
)


_RPCREPLY = _descriptor.Descriptor(
  name='RPCReply',
  full_name='RPCReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='RPCReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='RPCReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='RPCReply.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='RPCReply.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='RPCReply.file', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='RPCReply.text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=349,
)

_RPCREQUEST_FILESENTRY.fields_by_name['value'].message_type = _REQUESTFILES
_RPCREQUEST_FILESENTRY.containing_type = _RPCREQUEST
_RPCREQUEST.fields_by_name['files'].message_type = _RPCREQUEST_FILESENTRY
_REQUESTFILES.fields_by_name['files'].message_type = _REQUESTFILE
DESCRIPTOR.message_types_by_name['RPCRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RequestFiles'] = _REQUESTFILES
DESCRIPTOR.message_types_by_name['RequestFile'] = _REQUESTFILE
DESCRIPTOR.message_types_by_name['RPCReply'] = _RPCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCRequest = _reflection.GeneratedProtocolMessageType('RPCRequest', (_message.Message,), {

  'FilesEntry' : _reflection.GeneratedProtocolMessageType('FilesEntry', (_message.Message,), {
    'DESCRIPTOR' : _RPCREQUEST_FILESENTRY,
    '__module__' : 'common_pb2'
    # @@protoc_insertion_point(class_scope:RPCRequest.FilesEntry)
    })
  ,
  'DESCRIPTOR' : _RPCREQUEST,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:RPCRequest)
  })
_sym_db.RegisterMessage(RPCRequest)
_sym_db.RegisterMessage(RPCRequest.FilesEntry)

RequestFiles = _reflection.GeneratedProtocolMessageType('RequestFiles', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFILES,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:RequestFiles)
  })
_sym_db.RegisterMessage(RequestFiles)

RequestFile = _reflection.GeneratedProtocolMessageType('RequestFile', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFILE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:RequestFile)
  })
_sym_db.RegisterMessage(RequestFile)

RPCReply = _reflection.GeneratedProtocolMessageType('RPCReply', (_message.Message,), {
  'DESCRIPTOR' : _RPCREPLY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:RPCReply)
  })
_sym_db.RegisterMessage(RPCReply)


_RPCREQUEST_FILESENTRY._options = None
# @@protoc_insertion_point(module_scope)
