# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trident.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trident.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtrident.proto\x1a\x0c\x63ommon.proto23\n\x0cMicroService\x12#\n\x07Handler\x12\x0b.RPCRequest\x1a\t.RPCReply\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MICROSERVICE = _descriptor.ServiceDescriptor(
  name='MicroService',
  full_name='MicroService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=31,
  serialized_end=82,
  methods=[
  _descriptor.MethodDescriptor(
    name='Handler',
    full_name='MicroService.Handler',
    index=0,
    containing_service=None,
    input_type=common__pb2._RPCREQUEST,
    output_type=common__pb2._RPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MICROSERVICE)

DESCRIPTOR.services_by_name['MicroService'] = _MICROSERVICE

# @@protoc_insertion_point(module_scope)
