sys: "efunds"

logging:
  level: "debug"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "6NVH0SVXZEWH"
    db_name: "user_proxy"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    password: "I8TLQ8NQCT4L"
    db: 1
    expire_seconds: 86400
  sqlalchemy:
    echo: False

unify_auth:
  auto_create_user: True
  permission:
    pdflux:
      normal: "普通用户"
      admin: "管理员"
    calliper:
      normal: "普通用户"
      admin: "管理员"
    autodoc_overall:
      admin: "管理员"
      normal: "普通用户"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_pdflux:
      app_id: "pfbbackend"
      secret_key: "hello_pfbbackend"
      token_expire: 120
      host: ""
      subpath: "pdflux/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/common-logout"
    auth_calliper:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: ""
      subpath: "calliper/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_autodoc_overall:
      app_id: "autodoc"
      secret_key: "show-me-the-money"
      token_expire: 120
      host: ""
      subpath: "autodoc/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"


front_config:
  auto_redirect_sub_sys: False # 只有一个子系统，普通用户是否直接跳转到子系统
  user_manage: True # 展示用户管理界面
  sub_sys_config:
    calliper:
      open: false
      title: '文档智能对比'
    pdflux:
      open: true
      title: 'PDF表格智能提取'
    overall:
      open: true
      title: '全面复核'
  customer_role_permission_contrast:
    user_admin: '用户管理员'
    role_admin: '角色管理员'
