sys: "cms"

logging:
  level: "debug"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "I7FQ9T0S75"
    db_name: "user_proxy14"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 14
    expire_seconds: 86400
  sqlalchemy:
    echo: False

unify_auth:
  auto_create_user: True
  permission:
    autodoc_overall:
      normal: "普通用户"
      admin: "管理员"
    pdflux:
      normal: "普通用户"
    glazer:
      normal: "普通用户"
      admin: "管理员"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_autodoc_overall:
      app_id: "autodoc"
      secret_key: "show-me-the-money"
      token_expire: 120
      host: ""
      subpath: "autodoc/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_pdflux:
      app_id: "pdflux"
      secret_key: "Y4Yixw9zMfFsOQrK5VCh4VrI"
      token_expire: 120
      host: ""
      subpath: "pdflux/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_glazer:
      app_id: "glazer"
      secret_key: "hello_glazer"
      token_expire: 120
      host: ""
      subpath: "glazer/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

cms_auth:
  IASID: "01"
  IASKEY: "22362E7A9285DD53A0BBC2932F9733C505DC04EDBFE00D70"
  POSTURL: "http://10.254.253.237/login.aspx"
  AFTER_LOGIN: "api/v1/get-off"

front_config:
  user_manage: False # 展示用户管理界面
  auto_redirect_sub_sys: True # 只有一个子系统，普通用户是否直接跳转到子系统
  internal: False  # 标记内部环境，用于区分内外环境登录、退出等差异
  customer_login_api: '/cms/sso-login?app=autodoc_overall&custom_system=统一认证' # 未登录直接访问trident主页，跳转至客户认证界面接口
  pd_env: false  # 未登录直接访问trident /#/login页，跳转至客户认证界面接口
  sub_sys_config:
    overall:
      open: true
      title: '全面复核'
    pdflux:
      open: true
      title: 'PDF表格提取'
    glazer:
      open: true
      title: '智能撰写'
