sys: "dfjc"
logging:
  level: "info"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  binary_json: True
  binary_key: "f86f429d035efb84d682bddc8a07f8bf"
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "iZj5VqoZZEK5T2A"
    db_name: "trident"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 0
    password: "iZj5VqoZZEK5T2A"
    expire_seconds: 86400
  sqlalchemy:
    echo: False
  auth_common:
    enable: true
    app_id: "trident"
    secret_key: "7668accda83143b4b7d8a8db872f0ae3"
    token_expire: 900
    exclude_domain: true
    token_single_effective: True

unify_auth:
  auto_create_user: True
  show_role_manage: True
  allow_sys_admin_sso: False # 是否允许系统管理员使用单点登录
  permission:
    autodoc_overall:
      normal: "普通用户"
      admin: "管理员"
    metalmesh:
      normal: "普通用户"
      admin: "管理员"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_autodoc_overall:
      app_id: "autodoc"
      secret_key: "show-me-the-money"
      token_expire: 120
      host: ""
      internal_host: "http://autodoc:8000/absdoc"
      subpath: "autodoc/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_metalmesh:
      app_id: "metalmesh"
      secret_key: "hello_metalmesh"
      token_expire: 120
      host: "http://metalmesh"
      subpath: ""
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/common-logout"

front_config:
  auto_redirect_sub_sys: False # 只有一个子系统，普通用户是否直接跳转到子系统
  user_manage: True # 展示用户管理界面
  sub_sys_config:
    overall:
      open: true
      title: "文档智能复核"
    metalmesh:
      open: true
      title: "财务三大表智能提取核查"
