sys: "htsc"

logging:
  level: "info"

webif:
  debug: false
  http_port: 8000
  redirect_subpath: ""
  http_secure_map: # 关闭不安全的http方法
    PUT: POST
    DELETE: POST
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "ht9HCwom1p8c"
    db_name: "user_proxy"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 1
    password: "0rqWjWUEJZ4Z"
    expire_seconds: 86400
  sqlalchemy:
    echo: False

unify_auth:
  auto_create_user: True
  permission:
    calliper:
      normal: "普通用户"
      admin: "管理员"
    autodoc_overall:
      normal: "普通用户"
      admin: "管理员"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_calliper:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: "http://calliper"
      subpath: ""
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_autodoc_overall:
      app_id: "autodoc"
      secret_key: "show-me-the-money"
      token_expire: 120
      host: "http://autodoc"
      subpath: ""
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
      allowed_args: ['projectId', 'runId', 'confirm_tasktype']

front_config:
  sub_sys_config:
    overall:
      open: true
      title: '智能复核'
    calliper:
      open: true
      title: '文档智能对比'

htsc_auth:
  header_key: "X-EIPGW-USERID"
  secret_key: "eLIB6L2iHjci6xsmSW8pUqoxmGUnYAq8"
  oa_logout_url: "http://eipsit.htsc.com.cn/"
  department_enable: true
  department_host: "http://168.61.13.240:8080"
  department_api: "/lhzq.ibms/paodingStat/getOrgByUserId"
