sys: "gffunds"

logging:
  level: "info"

webif:
  debug: false
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "aik4riekeeb5Iekeev"
    db_name: "user_proxy"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 3
    password: "aik4riekeeb5Iekeev"
    expire_seconds: 10800
    renew_ttl: false
    single_sign_limit: False
  sqlalchemy:
    echo: False
  proxy_send_timeout: 60 # 启动时 entrypoint 根据此配置修改 nginx 及 gunicorn timeout 时间

unify_auth:
  auto_create_user: True
  permission:
    autodoc_overall:
      admin: "管理员"
      normal: "普通用户"
    scriber:
      remark: "标注"
      browse: "浏览"
      manage_prj: "管理项目"
      manage_user: "用户管理"
      manage_mold: "schema管理"
      manage_model: "模型管理"
      inspect: "审核"
      customer_rule_participate: "规则管理-自定义规则-经办"
      customer_rule_review: "规则管理-自定义规则-复核"
    calliper:
      admin: "管理员"
      normal: "普通用户"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_autodoc_overall:
      app_id: "autodoc"
      secret_key: "show-me-the-money"
      token_expire: 120
      host: "http://autodoc"
      subpath: ""
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_scriber:
      app_id: "remarkable"
      secret_key: "hello_remarkable"
      token_expire: 120
      host: ""
      subpath: "scriber/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_calliper:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: ""
      subpath: "calliper/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

front_config:
  auto_redirect_sub_sys: False # 只有一个子系统，普通用户是否直接跳转到子系统
  allow_change_password: True # 修改密码
  sub_sys_config:
    overall:
      open: true
      title: "文档智能审核"
    scriber:
      open: true
      title: "文档智能提取"
    calliper:
      open: true
      title: '文档智能对比'

sso_auth:
  url: "http://100.64.0.9:55811/api/v1/mock/gffunds/sso/authorize"
  sso_attribute_session_key: "SSO_ATTRIBUTE"