#Calliper对应的Trident配置

sys: "csits"

logging:
  level: "debug"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "6vPS8wv9FCQq"
    db_name: "user_proxy"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 1
    password: '6vPS8wv9FCQq'
    expire_seconds: 86400
  sqlalchemy:
    echo: False

unify_auth:
  auto_create_user: True
  permission:
    calliper:
      normal: "普通用户"
      admin: "管理员"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_calliper:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: "http://calliper"
      subpath: ""
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

front_config:
  customer_login_api: '/user/cas-login'
  pd_env: false  # 未登录直接访问trident /#/login页，跳转至客户认证界面接口
  sub_sys_config:
    calliper:
      open: true
      title: '文档智能对比'

cas_auth:
  server: ""
  cas_token_session_key: "ticket"
  cas_username_session_key: "CAS_USERNAME"
  cas_attributes_session_key: "CAS_ATTRIBUTES"
  cas_after_login: ""
  cas_after_logout: "/api/v1/user/cas-login?app=calliper"
  login_uri: "/cas/login"
  logout_uri: "/cas/logout"
  validate_uri: "/cas/serviceValidate"
  system_name: ''