sys: "sse"

logging:
  level: "info"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "trident-postgres"
    port: 5432
    user: "postgres"
    password: "VrDJrh0KN109"
    db_name: "trident"
    check_interval: 60
  session:
    host: "trident-redis"
    port: 6379
    db: 1
    password: "sOu6P6P6lN97"
    expire_seconds: 86400
  sqlalchemy:
    echo: False

unify_auth:
  auto_create_user: True
  permission:
    pdflux:
      normal: "普通用户"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_pdflux:
      app_id: "pfbbackend"
      secret_key: "hello_pfbbackend"
      token_expire: 120
      host: "http://pdflux"
      subpath: "pdflux/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

front_config:
  sub_sys_config:
    pdflux:
      open: true
      title: '金融文档表格提取'
