sys: "cgs"
#test: trident 100.64.0.9:55850

logging:
  level: "debug"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  binary_json: True
  binary_key: "ee5db41491a5704ba1a01db7e89819c0"
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "BrhnxjTvBwqi"
    db_name: "user_proxy"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 1
    password: "saRoFRgS"
    expire_seconds: 86400
  sqlalchemy:
    echo: False
  feature:
    check_captcha: true

unify_auth:
  auto_create_user: True
  permission:
    calliper:
      normal: "普通用户"
      admin: "管理员"
    calliper_similarity:
      normal: "普通用户"
      admin: "管理员"
    scriber:
      remark: "标注"
      browse: "浏览"
      manage_prj: "管理项目"
      # manage_user: "用户管理"
      manage_mold: "schema管理"
      manage_model: "模型管理"
      manage_law: "法规管理"
      inspect: "审核"
      customer_rule_participate: "规则管理-自定义规则-经办"
      customer_rule_review: "规则管理-自定义规则-复核"
      developed_rule_browse: "规则管理-研发规则"
    glazer:
      normal: "普通用户"
      admin: "管理员"
      template: "模板用户"
    chatdoc:
      normal: "普通用户"
      admin: "管理员"

  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_calliper:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: "" #test: 100.64.0.15:1211
      subpath: "calliper/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_calliper_similarity:
      app_id: "calliper"
      secret_key: "hello_calliper"
      token_expire: 120
      host: ""
      subpath: "calliper-similarity/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_scriber:
      app_id: "remarkable"
      secret_key: "hello_remarkable"
      token_expire: 120
      host: "" #test: 100.64.0.3:22105
      subpath: "scriber/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_glazer:
      app_id: "glazer"
      secret_key: "hello_glazer"
      token_expire: 120
      host: "http://glazer"
      subpath: "glazer/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"
    auth_chatdoc:
      app_id: "chatdoc"
      secret_key: "hello_chatdoc"
      token_expire: 120
      host: "http://chatdoc"
      subpath: "chatdoc/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

front_config:
  auto_redirect_sub_sys: False
  user_manage: True
  sub_sys_config:
    calliper:
      open: true
      title: "文档智能对比"
    calliper_similarity:
      open: true
      title: "文档智能查重"
    scriber:
      open: true
      title: "文件智能审核"
    glazer:
      open: true
      title: "文档智能撰写"
    chatdoc:
      open: true
      title: "智能文档问答"
      captions: "支持文档智能问答，进行快速查找与精准回答"

cas_auth:
  server: "https://iam-test.chinastock.com.cn"
  cas_token_session_key: "ticket"
  cas_username_session_key: "CAS_USERNAME"
  cas_attributes_session_key: "CAS_ATTRIBUTES"
  cas_after_login: ""
  cas_after_logout: ""
  login_uri: "/cas/login"
  logout_uri: "/cas/logout"
  validate_uri: "/cas/serviceValidate"
  system_name: ""

ldap:
  uri: ldap://10.8.9.5:636 # ldap 认证地址(10.8.9.1)
  search_base: DC=chinastock,DC=com,DC=cn # ldap搜索根节点
  filter: (&(objectCategory=Person)(sAMAccountName=%s))
  attrlist: ["o", "description", "cn"]
  admin_dn: IDPservice@chinastock.com.cn # 管理员账号
  admin_password: 3xR3HdedTo^Xgp # 管理员密码

#jwe_auth:
#  key_path: 'data/keys/cgs_prod_jwe_private_key.json'

cgs_esb:
  user: "sda"
  password: "rkTj3v8na2Sg4b"
  url: "http://10.4.27.52:22112/apiJson/V2/sda"
  check_func: "YH0041000200002"
  default_func_version: "1"
