sys: "guosen-foundry"

logging:
  level: "info"

webif:
  debug: False
  http_port: 8000
  redirect_subpath: ""
  postgresql:
    host: "postgres"
    port: 5432
    user: "postgres"
    password: "exah4Ueth3ooheow"
    db_name: "trident"
    check_interval: 60
  session:
    host: "redis"
    port: 6379
    db: 1
    password: 'exah4Ueth3ooheow'
  sqlalchemy:
    echo: False
  feature:
    check_captcha: true

unify_auth:
  auto_create_user: True
  permission:
    foundry:
      normal: "普通用户"
      admin: "管理员"
  auth_self:
    app_id: "user_proxy"
    secret_key: "I-do-not-know"
    token_expire: 120
  auth_config:
    auth_foundry:
      app_id: "foundry"
      secret_key: "hello_foundry"
      token_expire: 120
      host: ""
      subpath: "foundry/"
      auth_api: "api/v1/user/unify-login"
      logout_api: "api/v1/logout"

front_config:
  auto_redirect_sub_sys: False
  allow_change_password: True
  internal: False  # 标记内部环境，用于区分内外环境登录、退出等差异
  sub_sys_config:
    foundry:
      open: true
      title: "NLP标注与训练"
