[program:trident-kafka]
directory=/opt/trident
command=python3 user_proxy/devtools/kafka_logout.pyc
stderr_logfile=/data/logs/trident-kafka-stderr.log
stdout_logfile=/data/logs/trident-kafka-stdout.log
autostart=true
autorestart=true
stopasgroup=true
startsecs=5
